name: NWDog
favicon: null
layout_spectrum: 0.17712
typography_spectrum: 0.16356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171312'
    - '#393536'
    - '#fdd2ce'
    - '#d1a285'
    - '#635f5c'
  brandStrength: 0.125
  lightness: 0.4815763202495873
  saturation: 0.6933255302719772
  rhythmicContrast: 0.25
purpose: []
